import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const heroFonte = Ubuntu({
  subsets: ["latin"],
  weight : ["300" , "400", "500", "700"]
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt">
      <body className={heroFonte.className}>{children}</body>
    </html>
  );
}
